import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, CircleAlert, Orbit, Save, ShieldCheck } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { saveProfile } from "../services/api";
import Logo from "../components/Logo";

const steps = ["Basics", "Goal", "Risk", "Details", "Review"];
const initialForm = {
  user_id: getUserId(), name: "", age: "", employment_status: "", monthly_income: "", monthly_contribution: "",
  investment: { initial_amount: "", horizon: "", goal: "", custom_goal: "", target_amount: "", target_date: "" },
  risk_assessment: { temporary_loss: "", investment_time: "", capital_protection: "", value_fluctuations: "" },
  liquidity: { emergency_fund_status: "", coverage: "" }, existing_investments: [], preferred_categories: [],
};
const horizonOptions = [["less_than_1", "Less than 1 year"], ["one_to_three", "1–3 years"], ["three_to_five", "3–5 years"], ["five_to_ten", "5–10 years"], ["more_than_10", "More than 10 years"]];
const goals = [["education", "Education"], ["emergency_fund", "Emergency fund"], ["vehicle", "Buying a vehicle"], ["house", "Buying a house"], ["retirement", "Retirement"], ["wealth_creation", "Wealth creation"], ["business", "Business / startup"], ["marriage", "Marriage"], ["travel", "Travel"], ["other", "Other"]];
const investmentCategories = ["Stocks", "Mutual Funds", "Gold", "Bonds", "Fixed Deposits", "NPS", "PPF", "ETFs", "Other"];
const preferences = ["Equity", "Mutual Funds", "Gold", "Bonds", "Fixed Deposits", "NPS", "PPF", "ETFs", "No preference"];
const riskQuestions = [
  ["temporary_loss", "If your investment temporarily falls by 15%, what would you most likely do?", [["sell_most", "Sell most of it"], ["sell_some", "Sell some of it"], ["hold", "Hold"], ["invest_more", "Invest more"]]],
  ["investment_time", "How long can you leave this money invested?", horizonOptions],
  ["capital_protection", "How important is protecting the initial investment?", [["very_important", "Very important"], ["important", "Important"], ["moderate", "Moderate"], ["less_important", "Less important"]]],
  ["value_fluctuations", "How comfortable are you with investment value fluctuations?", [["very_uncomfortable", "Very uncomfortable"], ["slightly_uncomfortable", "Slightly uncomfortable"], ["neutral", "Neutral"], ["comfortable", "Comfortable"], ["very_comfortable", "Very comfortable"]]],
];

export default function ProfilePage() {
  const navigate = useNavigate();
  const [step, setStep] = useState(0);
  const [form, setForm] = useState(() => loadSavedForm());
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const update = (section, field, value) => setForm((current) => section ? { ...current, [section]: { ...current[section], [field]: value } } : { ...current, [field]: value });
  const toggle = (field, value) => setForm((current) => ({ ...current, [field]: current[field].includes(value) ? current[field].filter((item) => item !== value) : [...current[field], value] }));
  const next = () => { const message = validateStep(step, form); if (message) { setError(message); return; } setError(""); setStep((current) => Math.min(current + 1, steps.length - 1)); };
  const save = async () => { const message = validateStep(3, form); if (message) { setError(message); return; } setSaving(true); setError(""); try { const saved = await saveProfile(toApiPayload(form)); localStorage.setItem("investtwin.profile", JSON.stringify(saved)); navigate("/dashboard"); } catch (requestError) { setError("Unable to save your profile. Please check your connection and try again."); } finally { setSaving(false); } };
  return <div className="profile-page"><header className="profile-header"><Link to="/" className="profile-back"><ArrowLeft size={16} /> Exit setup</Link><Logo /><span className="profile-private"><ShieldCheck size={14} /> Private workspace</span></header><main className="profile-main"><div className="profile-intro"><span className="eyebrow"><Orbit size={14} /> Investor profile</span><h1>Let’s understand your starting point.</h1><p>A few thoughtful details will help InvestTwin organize your goals and circumstances. Nothing here is a recommendation.</p></div><div className="progress-row"><div className="progress-bar"><span style={{ width: `${(step / (steps.length - 1)) * 100}%` }} /></div><div className="step-label">Step {step + 1} of {steps.length} <strong>{steps[step]}</strong></div></div><section className="form-card">{step < 4 && <div className="form-heading"><span className="form-kicker">{String(step + 1).padStart(2, "0")} / {String(steps.length - 1).padStart(2, "0")}</span><h2>{["Tell us about you", "What are you preparing for?", "How do you relate to risk?", "The details around your plan"][step]}</h2><p>{["This stays with your profile and is used to understand your context.", "A goal gives your investment journey a direction and a time horizon.", "There is no right answer. Choose what feels most like you.", "These details help complete the picture without making any judgement."][step]}</p></div>}{step === 0 && <Basics form={form} update={update} />}{step === 1 && <Goal form={form} update={update} />}{step === 2 && <Risk form={form} update={update} />}{step === 3 && <Details form={form} update={update} toggle={toggle} />}{step === 4 && <Review form={form} />}{error && <div className="form-error"><CircleAlert size={17} />{error}</div>}<div className="form-actions">{step > 0 ? <button className="text-button" onClick={() => { setError(""); setStep((current) => current - 1); }}><ArrowLeft size={16} /> Back</button> : <span />}{step < 4 ? <button className="primary-button" onClick={next}>Continue <ArrowRight size={17} /></button> : <button className="primary-button" onClick={save} disabled={saving}><Save size={16} />{saving ? "Saving..." : "Save Profile"}</button>}</div></section></main></div>;
}

function Basics({ form, update }) { return <div className="field-grid"><Field label="Your name" value={form.name} onChange={(value) => update(null, "name", value)} placeholder="e.g. Arun Mehta" /><Field label="Age" type="number" value={form.age} onChange={(value) => update(null, "age", value)} placeholder="21" /><Select label="Employment status" value={form.employment_status} onChange={(value) => update(null, "employment_status", value)} options={[["employed", "Employed"], ["self_employed", "Self-employed"], ["student", "Student"], ["retired", "Retired"], ["other", "Other"]]} /><Field label="Monthly income" prefix="₹" type="number" value={form.monthly_income} onChange={(value) => update(null, "monthly_income", value)} placeholder="50,000" /><Field label="Monthly savings / contribution" prefix="₹" type="number" value={form.monthly_contribution} onChange={(value) => update(null, "monthly_contribution", value)} placeholder="2,000" /></div>; }
function Goal({ form, update }) { return <div className="form-stack"><Field label="Initial investment amount" prefix="₹" type="number" value={form.investment.initial_amount} onChange={(value) => update("investment", "initial_amount", value)} placeholder="10,000" /><div><label className="field-label">What is your primary financial goal?</label><div className="choice-grid">{goals.map(([value, label]) => <Choice key={value} selected={form.investment.goal === value} label={label} onClick={() => update("investment", "goal", value)} />)}</div></div>{form.investment.goal === "other" && <Field label="Tell us about your goal" value={form.investment.custom_goal} onChange={(value) => update("investment", "custom_goal", value)} placeholder="e.g. A sabbatical" />}<Field label="Target amount" prefix="₹" type="number" value={form.investment.target_amount} onChange={(value) => update("investment", "target_amount", value)} placeholder="5,00,000" /><Field label="Target date (optional)" type="date" value={form.investment.target_date} onChange={(value) => update("investment", "target_date", value)} /></div>; }
function Risk({ form, update }) { return <div className="form-stack">{riskQuestions.map(([field, question, options]) => <div className="question-block" key={field}><label className="field-label">{question}</label><div className="choice-grid">{options.map(([value, label]) => <Choice key={value} selected={form.risk_assessment[field] === value} label={label} onClick={() => update("risk_assessment", field, value)} />)}</div></div>)}<div className="risk-note"><ShieldCheck size={16} /><span>Your responses create an application-defined profile such as Conservative, Moderate, Growth, or Aggressive. It is not a universal financial assessment.</span></div></div>; }
function Details({ form, update, toggle }) { return <div className="form-stack"><div><label className="field-label">Do you have an emergency fund?</label><div className="choice-grid two-col">{[["yes", "Yes"], ["no", "No"], ["partially", "Partially"]].map(([value, label]) => <Choice key={value} selected={form.liquidity.emergency_fund_status === value} label={label} onClick={() => update("liquidity", "emergency_fund_status", value)} />)}</div></div>{form.liquidity.emergency_fund_status === "yes" && <Select label="Approximately how many months of expenses does it cover?" value={form.liquidity.coverage} onChange={(value) => update("liquidity", "coverage", value)} options={[["less_than_1", "Less than 1 month"], ["one_to_three", "1–3 months"], ["three_to_six", "3–6 months"], ["more_than_6", "More than 6 months"]]} />}{form.liquidity.emergency_fund_status !== "yes" && form.liquidity.emergency_fund_status && <Select label="Emergency fund coverage" value={form.liquidity.coverage} onChange={(value) => update("liquidity", "coverage", value)} options={[["less_than_1", "Less than 1 month"], ["one_to_three", "1–3 months"], ["three_to_six", "3–6 months"], ["more_than_6", "More than 6 months"]]} />}<ChoiceList label="Existing investments" hint="Select any categories you already hold." values={form.existing_investments} options={investmentCategories} onToggle={(value) => toggle("existing_investments", value)} /><ChoiceList label="Preferred categories" hint="These are preferences, not recommendations." values={form.preferred_categories} options={preferences} onToggle={(value) => toggle("preferred_categories", value)} /><Select label="Investment horizon" value={form.investment.horizon} onChange={(value) => update("investment", "horizon", value)} options={horizonOptions} /></div>; }
function Review({ form }) { return <div className="review-grid"><ReviewItem label="Name" value={`${form.name}, ${form.age}`} /><ReviewItem label="Monthly income / contribution" value={`${money(form.monthly_income)} / ${money(form.monthly_contribution)}`} /><ReviewItem label="Investment amount" value={money(form.investment.initial_amount)} /><ReviewItem label="Goal" value={goals.find(([value]) => value === form.investment.goal)?.[1] || "—"} /><ReviewItem label="Target" value={`${money(form.investment.target_amount)}${form.investment.target_date ? ` by ${form.investment.target_date}` : ""}`} /><ReviewItem label="Horizon" value={labelFor(horizonOptions, form.investment.horizon)} /><ReviewItem label="Emergency fund" value={labelFor([["yes", "Yes"], ["no", "No"], ["partially", "Partially"]], form.liquidity.emergency_fund_status)} /><ReviewItem label="Existing investments" value={form.existing_investments.join(", ") || "None declared"} /><div className="review-disclaimer"><Check size={17} />Profile data is user-provided. InvestTwin will not make a recommendation from this information at this stage.</div></div>; }
function Field({ label, value, onChange, type = "text", prefix, placeholder }) { return <label className="field-label">{label}<span className={prefix ? "input-wrap" : ""}>{prefix && <span className="input-prefix">{prefix}</span>}<input type={type} value={value} min={type === "number" ? "0" : undefined} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /></span></label>; }
function Select({ label, value, onChange, options }) { return <label className="field-label">{label}<select value={value} onChange={(event) => onChange(event.target.value)}><option value="">Choose one</option>{options.map(([optionValue, optionLabel]) => <option key={optionValue} value={optionValue}>{optionLabel}</option>)}</select></label>; }
function Choice({ label, selected, onClick }) { return <button type="button" className={`choice ${selected ? "choice-selected" : ""}`} onClick={onClick}>{selected && <Check size={14} />}{label}</button>; }
function ChoiceList({ label, hint, values, options, onToggle }) { return <div><label className="field-label">{label}<small>{hint}</small></label><div className="tag-list">{options.map((option) => <Choice key={option} label={option} selected={values.includes(option)} onClick={() => onToggle(option)} />)}</div></div>; }
function ReviewItem({ label, value }) { return <div className="review-item"><span>{label}</span><strong>{value}</strong></div>; }
function validateStep(step, form) { if (step === 0 && (!form.name.trim() || !form.age || Number(form.age) <= 0 || !form.employment_status || form.monthly_income === "" || Number(form.monthly_income) < 0 || form.monthly_contribution === "" || Number(form.monthly_contribution) < 0)) return "Please complete your basic information with valid non-negative amounts."; if (step === 1 && (!form.investment.initial_amount || Number(form.investment.initial_amount) < 0 || !form.investment.goal || (form.investment.goal === "other" && !form.investment.custom_goal.trim()) || !form.investment.target_amount || Number(form.investment.target_amount) <= 0)) return "Please choose a goal and enter a positive target amount."; if (step === 2 && Object.values(form.risk_assessment).some((value) => !value)) return "Please answer each risk question before continuing."; if (step === 3 && (!form.investment.horizon || !form.liquidity.emergency_fund_status)) return "Please choose an investment horizon and emergency fund status."; return ""; }
function toApiPayload(form) { return { ...form, age: Number(form.age), monthly_income: Number(form.monthly_income), monthly_contribution: Number(form.monthly_contribution), investment: { ...form.investment, initial_amount: Number(form.investment.initial_amount), target_amount: Number(form.investment.target_amount), target_date: form.investment.target_date || null } }; }
function labelFor(options, value) { return options.find(([optionValue]) => optionValue === value)?.[1] || "—"; }
function money(value) { return value === "" || value === undefined ? "—" : `₹${Number(value).toLocaleString("en-IN")}`; }
function getUserId() { const existing = localStorage.getItem("investtwin.user_id"); if (existing) return existing; const id = `user-${crypto.randomUUID()}`; localStorage.setItem("investtwin.user_id", id); return id; }
function loadSavedForm() { try { const saved = JSON.parse(localStorage.getItem("investtwin.profile")); return saved ? { ...initialForm, ...saved, risk_assessment: saved.risk_assessment?.answers || initialForm.risk_assessment } : initialForm; } catch { return initialForm; } }